apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-pipeline
secrets:
- name: harbor-registry-secret
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: github-pipeline
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-pipeline
subjects:
- kind: ServiceAccount
  name: github-pipeline