---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-secret
type: Opaque
stringData:
  secretToken: __GITHUB_WEBHOOK_SECRET__
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-trigger-template
spec:
  params:
    - name: gitRepository
    - name: gitBranch
    - name: gitRevision
    - name: gitUrl
    - name: imageRepository
    - name: pathToContext
    - name: pathToYamlFile
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: github-pr-
      spec:
        pipelineRef:
          name: build-and-deploy
        params:
          - name: gitUrl
            value: $(tt.params.gitUrl)
          - name: gitRevision
            value: $(tt.params.gitRevision)
          - name: pathToContext
            value: $(tt.params.pathToContext)
          - name: pathToYamlFile
            value: $(tt.params.pathToYamlFile)
          - name: imageUrl
            value: $(tt.params.imageRepository)/$(tt.params.gitRepository)
          - name: imageTag
            value: $(tt.params.gitBranch)
        serviceAccountName: github-pipeline
        workspaces:
          - name: git-source
            persistentVolumeClaim:
              claimName: github-source-pvc
            # If using volumeClaimTemplate, every time a PVC will be created for a PipelineRun
            # volumeClaimTemplate:
            #   metadata:
            #     name: git-source-pvc
            #   spec:
            #     accessModes: ["ReadWriteOnce"]
            #     resources:
            #       requests:
            #         storage: 4Gi              
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-trigger-binding
spec:
  params:
    - name: gitRepository
      value: $(body.repository.name)
    - name: gitBranch
      value: $(extensions.branch_name)
    - name: gitRevision
      value: $(body.pull_request.head.sha)
    - name: gitUrl
      value: $(body.repository.clone_url)
    - name: imageRepository
      value: __IMAGE_REPOSITORY__
    - name: pathToContext
      value: __PATH_TO_CONTEXT__
    - name: pathToYamlFile
      value: __PATH_TO_YAML_FILE__
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
spec:
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["pull_request"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'reopened']"            
            - name: "overlays"
              value:
                - key: branch_name
                  expression: "body.pull_request.head.ref"
                  #expression: "body.ref.split('/')[2]"
      bindings:
        - ref: github-trigger-binding
      template:
        ref: github-trigger-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: github-trigger
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"

