apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  namespace: postfix
  labels:
    name: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      restartPolicy: Always
      containers:
        - image: boky/postfix
          imagePullPolicy: IfNotPresent
          name: postfix
          env:
          - name: ALLOWED_SENDER_DOMAINS
            value: msazure.club
---
apiVersion: v1
kind: Service
metadata:
  name: postfix
  namespace: postfix
spec:
  selector:
    app: postfix
  ports:  
  - name: smtp
    protocol: TCP
    port: 587
    targetPort: 587

